# Language 

language: php
php:
  - "5.3"
# Global environment variables
env:
  global:
    - secure: "nIqSSbU/CCRF1UjikWnVhlLvnKfMpELAVS34aDC7iNSr2UrUPGb2acd33dlrwRm8SsgUB6irirgKvd1mYELvzzH+D1GiqHuKFHAgcBZpebRuUXRV0tPXGJmHdCVJjyxA37795fAp4lftJ+UKiXUN5EwNaCLlUnJw+vhXWqIj7ww="
    - secure: "r1FFuWaXPWdjVdL9mRAZ6HBkW2z/KmPFHeX27vGP0+HLG+KUmIS/tlg2umKnnsFQS3Hn8Ll9wqYBogV6c8DQJ2yqpMyzgY9dCBYzaTDIs2jMf8srAAQyko9k3pRpRcA1wm65+j6FbWz0vAZMfPup7caOtzf/WDy3elIdsY6FYW4="
    - secure: "Att/ULVmmTRhzaSgnaxGixKu0FkncYr7U5GqprD+dkKTDUXuFGq0ru8s0FiO1pDDbEZaiL+wAbjllbhu8mOTr7WeVrdteRPxYd5Q1KSXBoptjXDJ61yXuvBje2XEo1FcpP/r3novrov+eINALaGYNB0L0oACbJSIutrWNravX/g="
    - secure: "foKpT4DDThLR+fGQC7v/N0YWTNQeklt1f52r255rmffIMC3S+1n0ZH5afpzhbI0WhvcA3YPo+sbzucdAutt1lTSjt40axOArXiJb4ZdnT+2NwRpZ0hS8LnNXG8W8Bpbl2o3wAYf3e6ok/7rxMrsHNKShi1hdhQ7j9SeuN+neGWE="

# Install required packages
# Fix for See https://github.com/Jasig/sass-maven-plugin/issues/47
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sshpass
  - unset GEM_PATH
