# Language 

language: php
php:
  - "5.3"
# Global environment variables
env:
  global:
    - secure: "zBHrPo1QiZwMPBCThfhb+zK7VqZIGt1hM6VIV2VUhhdLZrleM8iFWFzAIMfdtPvgFZzxqewCTeEc8tAmDySlMVwrN78mHhyCR98B9gZldEqOgvxntGX5VMqj7N/CiQUknUk5w9zmO9S8Wq0IBCN2W/fVmYFuN3EeknmitPt5t0I="
# Install required packages
# Fix for See https://github.com/Jasig/sass-maven-plugin/issues/47
before_install:
  - unset GEM_PATH
# omitting "script:" will default to phpunit
script: phpunit --version
# Tell staging to pull latest code from git
after_success:
  - wget DEPLOY_PING